
spring:
  application:
    name: basic
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  config:
    import:
      - classpath:application-dao.yml
      - classpath:application-common.yml
